---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu
    image: "docker.io/schuam/podman_ubuntu2204_ansible:latest"
    pre_build_image: true
  - name: arch
    image: "docker.io/schuam/podman_archlinux_ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
